---
title: SlimDay Londrina
author: jair carrion
email: support@forestry.io
description: Kits perfeitos para você desinchar e acelerar o metabolismo!
baseurl: "/ubuild-jekyll"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
